name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-11-08"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow-db"
database_id = "d8b7c9f2-2bfd-490d-952d-3265a2544282"
