name: Sync Upstream

on:
  schedule:
    # 每天北京时间 00:00 运行（UTC 16:00）
    - cron: '0 16 * * *'
  # 也允许手动触发
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/ourongxing/newsnow.git
      
      - name: Fetch upstream
        run: |
          git fetch upstream
      
      - name: Merge upstream
        run: |
          git merge upstream/main --no-edit
      
      - name: Push changes
        run: |
          git push origin main
